$(".modal").iziModal({
    title: ' ',
    subtitle: ' ',
    headerColor: '#000000',
    background: null,
    theme: '',  // light
    attached: top,
    icon: null,
    iconText: null,
    iconColor: '',
    rtl: false,
    width: 850,
    bottom: null,
    borderBottom: false,
    padding: 0,
    radius: 3,
    zindex: 999,
    iframe: false,
    iframeURL: null,
    focusInput: true,
    group: 'Cars',
    loop: true,
    arrowKeys: true,
    navigateCaption: true,
    navigateArrows: true,  // Boolean, 'closeToModal', 'closeScreenEdge'
    history: false,
    restoreDefaultContent: false,
    autoOpen: false, // Boolean, Number
    bodyOverflow: true,
    fullscreen: false,
    openFullscreen: false,
    closeOnEscape: true,
    closeButton: true,
    appendTo: 'body', // or false
    appendToOverlay: 'body', // or false
    overlay: false,
    overlayClose: false,
    overlayColor: 'rgba(0, 0, 0, 0.4)',
    timeout: false,
    timeoutProgressbar: false,
    pauseOnHover: false,
    timeoutProgressbarColor: 'rgba(0, 0, 0, 0.5)',
    transitionIn: 'comingIn',
    transitionOut: 'comingOut',
    transitionInOverlay: 'fadeIn',
    transitionOutOverlay: 'fadeOut',
});
